language: python

env:
  - CODECOV_TOKEN="2cfcf295-ea5e-4f86-a596-fea8a850f11f"

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

script:
  - find ./htmtensorflow/ -name '*.py' -print0 | xargs -0 python -m coverage run -a -m doctest -o NORMALIZE_WHITESPACE -v
  - python -m coverage report

after_success:
  - codecov