language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  find ./htmtensorflow/ -name '*.py' -print0 | xargs -0 python -m doctest -o NORMALIZE_WHITESPACE -v